import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const isTablet = width > 768;
const isDesktop = width > 992;

const DARK_PURPLE = '#1F1C2F';
const LIGHT_PURPLE = '#8B7AB8';
const BRIGHT_PURPLE = '#A78BFA';
const WHITE = '#ffffff';
const TEXT_LIGHT = '#D1D5DB';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DARK_PURPLE,
  },
  gradient: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: isDesktop ? 60 : isTablet ? 40 : 24,
    paddingTop: isDesktop ? 80 : 60,
    paddingBottom: 80,
    maxWidth: 1600,
    alignSelf: 'center',
    width: '100%',
  },
  heroSection: {
    marginBottom: 64,
    position: 'relative',
    alignItems: 'center',
    minHeight: 300,
    justifyContent: 'center',
  },
  heroVisualContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0.15,
  },
  heroCircle1: {
    position: 'absolute',
    width: 400,
    height: 400,
    borderRadius: 200,
    borderWidth: 2,
    borderColor: BRIGHT_PURPLE,
    top: -100,
    left: -100,
  },
  heroCircle2: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    borderWidth: 2,
    borderColor: LIGHT_PURPLE,
    bottom: -50,
    right: -50,
  },
  heroCircle3: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 2,
    borderColor: BRIGHT_PURPLE,
    top: 50,
    right: 100,
  },
  heroContent: {
    alignItems: 'center',
    maxWidth: 900,
    zIndex: 1,
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.3)',
    marginBottom: 24,
    gap: 8,
  },
  badgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: BRIGHT_PURPLE,
  },
  badgeText: {
    fontSize: 13,
    fontWeight: '600',
    color: BRIGHT_PURPLE,
    letterSpacing: 0.5,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  heroTitle: {
    fontSize: isDesktop ? 72 : isTablet ? 56 : 42,
    fontWeight: 'bold',
    color: WHITE,
    marginBottom: 24,
    textAlign: 'center',
    lineHeight: isDesktop ? 84 : isTablet ? 64 : 50,
    fontFamily: Platform.select({
      web: 'Georgia, serif',
      default: 'serif',
    }),
    textShadowColor: LIGHT_PURPLE,
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 24,
  },
  heroTitleAccent: {
    color: BRIGHT_PURPLE,
    textShadowColor: BRIGHT_PURPLE,
  },
  heroDescription: {
    fontSize: isDesktop ? 22 : 20,
    color: TEXT_LIGHT,
    textAlign: 'center',
    lineHeight: 32,
    opacity: 0.9,
    maxWidth: 700,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  statsSection: {
    flexDirection: isDesktop ? 'row' : isTablet ? 'row' : 'column',
    gap: 20,
    marginBottom: 64,
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  statCard: {
    flex: isDesktop ? 1 : isTablet ? 0.48 : 1,
    backgroundColor: '#2D1B3D',
    borderRadius: 24,
    padding: 32,
    borderWidth: 1.5,
    borderColor: 'rgba(139, 122, 184, 0.2)',
    alignItems: 'center',
    minWidth: isTablet ? 200 : '100%',
    maxWidth: isDesktop ? 280 : '100%',
    shadowColor: LIGHT_PURPLE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 6,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'default',
      },
    }),
  },
  statCardHover: {
    transform: [{ translateY: -4 }, { scale: 1.02 }],
    borderColor: BRIGHT_PURPLE,
    shadowOpacity: 0.3,
    shadowRadius: 24,
    backgroundColor: '#3D2B4D',
  },
  statIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(167, 139, 250, 0.3)',
  },
  statIcon: {
    width: 32,
    height: 32,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statBriefcase: {
    width: 24,
    height: 18,
    borderRadius: 3,
    borderWidth: 2.5,
    borderColor: BRIGHT_PURPLE,
  },
  statDocument: {
    width: 20,
    height: 26,
    borderRadius: 2,
    borderWidth: 2.5,
    borderColor: BRIGHT_PURPLE,
  },
  statCalendar: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 2.5,
    borderColor: BRIGHT_PURPLE,
  },
  statStar: {
    width: 24,
    height: 24,
    borderWidth: 2.5,
    borderColor: BRIGHT_PURPLE,
    transform: [{ rotate: '45deg' }],
  },
  statValue: {
    fontSize: 36,
    fontWeight: 'bold',
    color: WHITE,
    marginBottom: 8,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  statLabel: {
    fontSize: 15,
    color: TEXT_LIGHT,
    opacity: 0.8,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  tabsSection: {
    marginBottom: 48,
    width: '100%',
  },
  tabsContainer: {
    flexDirection: 'row',
    gap: 16,
    flexWrap: 'wrap',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 16,
    backgroundColor: 'rgba(139, 122, 184, 0.1)',
    borderWidth: 1.5,
    borderColor: 'rgba(139, 122, 184, 0.3)',
    gap: 10,
    position: 'relative',
    minWidth: 180,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  tabActive: {
    backgroundColor: LIGHT_PURPLE,
    borderColor: LIGHT_PURPLE,
    shadowColor: LIGHT_PURPLE,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10,
  },
  tabText: {
    color: TEXT_LIGHT,
    fontSize: 16,
    fontWeight: '500',
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  tabTextActive: {
    color: WHITE,
    fontWeight: '600',
  },
  tabIndicator: {
    position: 'absolute',
    bottom: 0,
    left: '50%',
    marginLeft: -20,
    width: 40,
    height: 3,
    borderRadius: 2,
    backgroundColor: WHITE,
  },
  checkmarkContainer: {
    width: 18,
    height: 18,
    position: 'relative',
  },
  checkmarkLine1: {
    position: 'absolute',
    left: 4,
    bottom: 6,
    width: 8,
    height: 2.5,
    backgroundColor: WHITE,
    transform: [{ rotate: '-45deg' }],
  },
  checkmarkLine2: {
    position: 'absolute',
    left: 6,
    bottom: 4,
    width: 10,
    height: 2.5,
    backgroundColor: WHITE,
    transform: [{ rotate: '45deg' }],
  },
  searchSection: {
    marginBottom: 64,
    width: '100%',
    alignItems: 'center',
  },
  searchWrapper: {
    width: '100%',
    maxWidth: 1000,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: WHITE,
    borderRadius: 24,
    paddingHorizontal: 28,
    paddingVertical: 20,
    width: '100%',
    borderWidth: 2,
    borderColor: 'rgba(139, 122, 184, 0.2)',
    shadowColor: LIGHT_PURPLE,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 12,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
      },
    }),
  },
  searchBarFocused: {
    borderColor: BRIGHT_PURPLE,
    shadowOpacity: 0.3,
    shadowRadius: 32,
    ...Platform.select({
      web: {
        boxShadow: `0 12px 40px rgba(167, 139, 250, 0.4)`,
      },
    }),
  },
  searchIconContainer: {
    marginRight: 20,
  },
  searchIcon: {
    width: 24,
    height: 24,
    position: 'relative',
  },
  searchIconCircle: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 3,
    borderColor: '#6B7280',
    top: 0,
    left: 0,
  },
  searchIconLine: {
    position: 'absolute',
    width: 10,
    height: 3,
    backgroundColor: '#6B7280',
    transform: [{ rotate: '45deg' }],
    bottom: 2,
    right: 2,
  },
  searchInput: {
    flex: 1,
    color: '#1F2937',
    fontSize: 18,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  searchDivider: {
    width: 1,
    height: 32,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 20,
  },
  searchFilters: {
    flexDirection: 'row',
    gap: 12,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: LIGHT_PURPLE,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 12,
    gap: 8,
    ...Platform.select({
      web: {
        transition: 'all 0.2s ease',
        cursor: 'pointer',
      },
    }),
  },
  filterChipText: {
    color: WHITE,
    fontSize: 15,
    fontWeight: '600',
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  filterArrowIcon: {
    width: 12,
    height: 12,
    position: 'relative',
  },
  filterArrowUp: {
    position: 'absolute',
    top: 0,
    left: 4,
    width: 0,
    height: 0,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderBottomWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: WHITE,
  },
  filterArrowDown: {
    position: 'absolute',
    bottom: 0,
    left: 4,
    width: 0,
    height: 0,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: WHITE,
  },
  searchHint: {
    marginTop: 16,
    paddingLeft: 28,
  },
  searchHintText: {
    fontSize: 14,
    color: TEXT_LIGHT,
    opacity: 0.7,
    fontStyle: 'italic',
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  featuredSection: {
    width: '100%',
  },
  featuredHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 32,
  },
  featuredTitle: {
    fontSize: isDesktop ? 32 : 28,
    fontWeight: 'bold',
    color: WHITE,
    fontFamily: Platform.select({
      web: 'Georgia, serif',
      default: 'serif',
    }),
    textShadowColor: LIGHT_PURPLE,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 12,
  },
  viewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: 'rgba(139, 122, 184, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(139, 122, 184, 0.3)',
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  viewAllText: {
    color: BRIGHT_PURPLE,
    fontSize: 15,
    fontWeight: '600',
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  viewAllArrow: {
    width: 16,
    height: 16,
    position: 'relative',
  },
  arrowLine: {
    position: 'absolute',
    left: 0,
    top: 7,
    width: 12,
    height: 2,
    backgroundColor: BRIGHT_PURPLE,
  },
  arrowHead: {
    position: 'absolute',
    right: 0,
    top: 4,
    width: 0,
    height: 0,
    borderTopWidth: 4,
    borderBottomWidth: 4,
    borderLeftWidth: 6,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: BRIGHT_PURPLE,
  },
  featuredGrid: {
    flexDirection: isDesktop ? 'row' : isTablet ? 'row' : 'column',
    gap: 24,
    flexWrap: 'wrap',
  },
  featuredCard: {
    flex: isDesktop ? 1 : isTablet ? 0.48 : 1,
    backgroundColor: '#2D1B3D',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1.5,
    borderColor: 'rgba(139, 122, 184, 0.2)',
    minWidth: isTablet ? 280 : '100%',
    maxWidth: isDesktop ? 400 : '100%',
    shadowColor: LIGHT_PURPLE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 6,
  },
  featuredCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 20,
    gap: 16,
  },
  featuredCompanyLogo: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(167, 139, 250, 0.3)',
  },
  companyLogoCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: BRIGHT_PURPLE,
  },
  featuredCardContent: {
    flex: 1,
  },
  featuredJobTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: WHITE,
    marginBottom: 6,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  featuredCompanyName: {
    fontSize: 15,
    color: TEXT_LIGHT,
    opacity: 0.8,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  featuredBookmark: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookmarkIcon: {
    width: 20,
    height: 20,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 2,
    borderBottomWidth: 8,
    borderColor: TEXT_LIGHT,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    opacity: 0.5,
  },
  featuredCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  featuredTag: {
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.3)',
  },
  featuredTagText: {
    fontSize: 13,
    color: BRIGHT_PURPLE,
    fontWeight: '500',
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  featuredTime: {
    fontSize: 13,
    color: TEXT_LIGHT,
    opacity: 0.6,
    marginLeft: 'auto',
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
});

export default styles;
