import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const isTablet = width > 768;
const isDesktop = width > 992;

const DARK_PURPLE = '#1F1C2F';
const LIGHT_PURPLE = '#8B7AB8';
const BRIGHT_PURPLE = '#A78BFA';
const WHITE = '#ffffff';
const TEXT_LIGHT = '#D1D5DB';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DARK_PURPLE,
  },
  gradient: {
    flex: 1,
  },
  contentContainer: {
    flex: 1,
    flexDirection: isDesktop ? 'row' : 'column',
  },
  sidebar: {
    width: isDesktop ? 320 : '100%',
    padding: isDesktop ? 32 : 24,
    backgroundColor: '#2D1B3D',
    borderRightWidth: isDesktop ? 1.5 : 0,
    borderRightColor: 'rgba(139, 122, 184, 0.2)',
    borderBottomWidth: isDesktop ? 0 : 1.5,
    borderBottomColor: 'rgba(139, 122, 184, 0.2)',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 40,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(139, 122, 184, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(139, 122, 184, 0.2)',
    alignSelf: 'flex-start',
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  backButtonHover: {
    backgroundColor: 'rgba(139, 122, 184, 0.2)',
    borderColor: LIGHT_PURPLE,
  },
  backArrow: {
    width: 20,
    height: 20,
    position: 'relative',
  },
  backArrowLine: {
    position: 'absolute',
    left: 0,
    top: 9,
    width: 12,
    height: 2,
    backgroundColor: WHITE,
  },
  backArrowHead: {
    position: 'absolute',
    left: 0,
    top: 4,
    width: 0,
    height: 0,
    borderTopWidth: 6,
    borderBottomWidth: 6,
    borderLeftWidth: 8,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: WHITE,
  },
  backButtonText: {
    color: WHITE,
    fontSize: 15,
    fontWeight: '500',
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  actionButtons: {
    gap: 16,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(139, 122, 184, 0.3)',
    backgroundColor: 'rgba(139, 122, 184, 0.1)',
    gap: 12,
    shadowColor: LIGHT_PURPLE,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  primaryActionButton: {
    backgroundColor: LIGHT_PURPLE,
    borderColor: LIGHT_PURPLE,
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  actionButtonHover: {
    transform: [{ translateY: -2 }],
    borderColor: BRIGHT_PURPLE,
    backgroundColor: isDesktop ? BRIGHT_PURPLE : LIGHT_PURPLE,
    shadowOpacity: 0.4,
    shadowRadius: 16,
  },
  actionButtonIcon: {
    width: 24,
    height: 24,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyIcon: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2.5,
    borderColor: WHITE,
  },
  interviewIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2.5,
    borderColor: WHITE,
  },
  letterIcon: {
    width: 20,
    height: 16,
    borderRadius: 2,
    borderWidth: 2.5,
    borderColor: WHITE,
  },
  resumeIcon: {
    width: 16,
    height: 20,
    borderRadius: 2,
    borderWidth: 2.5,
    borderColor: WHITE,
  },
  actionButtonText: {
    color: WHITE,
    fontSize: 15,
    fontWeight: '600',
    flex: 1,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 60,
  },
  contentWrapper: {
    maxWidth: 900,
    alignSelf: 'center',
    width: '100%',
    padding: isDesktop ? 48 : isTablet ? 40 : 32,
    paddingTop: isDesktop ? 60 : 48,
  },
  jobHeader: {
    marginBottom: 48,
    paddingBottom: 32,
    borderBottomWidth: 1.5,
    borderBottomColor: 'rgba(139, 122, 184, 0.2)',
  },
  jobHeaderLeft: {
    flexDirection: 'row',
    gap: 20,
    flex: 1,
  },
  companyLogo: {
    width: 80,
    height: 80,
    borderRadius: 20,
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(167, 139, 250, 0.3)',
  },
  companyLogoText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: BRIGHT_PURPLE,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  jobHeaderContent: {
    flex: 1,
  },
  jobHeaderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  companyName: {
    fontSize: 18,
    fontWeight: '600',
    color: TEXT_LIGHT,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  matchBadge: {
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.3)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  matchScore: {
    fontSize: 16,
    fontWeight: 'bold',
    color: BRIGHT_PURPLE,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  matchLabel: {
    fontSize: 12,
    color: TEXT_LIGHT,
    opacity: 0.7,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  jobTitle: {
    fontSize: isDesktop ? 36 : isTablet ? 32 : 28,
    fontWeight: 'bold',
    color: WHITE,
    marginBottom: 20,
    lineHeight: isDesktop ? 44 : isTablet ? 40 : 36,
    fontFamily: Platform.select({
      web: 'Georgia, serif',
      default: 'serif',
    }),
    textShadowColor: LIGHT_PURPLE,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 12,
  },
  jobMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
  },
  jobMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  metaIcon: {
    width: 20,
    height: 20,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: TEXT_LIGHT,
    opacity: 0.7,
  },
  typeIcon: {
    width: 16,
    height: 16,
    borderWidth: 2,
    borderColor: TEXT_LIGHT,
    transform: [{ rotate: '45deg' }],
    opacity: 0.7,
  },
  moneyIcon: {
    width: 16,
    height: 16,
    borderWidth: 2,
    borderColor: TEXT_LIGHT,
    transform: [{ rotate: '45deg' }],
    opacity: 0.7,
  },
  metaText: {
    fontSize: 15,
    color: TEXT_LIGHT,
    opacity: 0.9,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  bookmarkButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: 'rgba(139, 122, 184, 0.1)',
    borderWidth: 1.5,
    borderColor: 'rgba(139, 122, 184, 0.3)',
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  bookmarkIcon: {
    width: 24,
    height: 24,
    position: 'relative',
  },
  bookmarkIconActive: {
    opacity: 1,
  },
  bookmarkShape: {
    width: 20,
    height: 20,
    borderLeftWidth: 2.5,
    borderRightWidth: 2.5,
    borderTopWidth: 2.5,
    borderBottomWidth: 8,
    borderColor: TEXT_LIGHT,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    opacity: 0.6,
  },
  section: {
    marginBottom: 48,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 24,
  },
  sectionIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(167, 139, 250, 0.3)',
  },
  aboutIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2.5,
    borderColor: BRIGHT_PURPLE,
  },
  responsibilitiesIcon: {
    width: 28,
    height: 28,
    borderWidth: 2.5,
    borderColor: BRIGHT_PURPLE,
    transform: [{ rotate: '45deg' }],
  },
  qualificationsIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2.5,
    borderColor: BRIGHT_PURPLE,
  },
  sectionHeading: {
    fontSize: isDesktop ? 28 : 24,
    fontWeight: 'bold',
    color: WHITE,
    fontFamily: Platform.select({
      web: 'Georgia, serif',
      default: 'serif',
    }),
    textShadowColor: LIGHT_PURPLE,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  paragraph: {
    fontSize: 17,
    color: TEXT_LIGHT,
    lineHeight: 28,
    marginBottom: 20,
    opacity: 0.9,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  sectionSubtext: {
    fontSize: 17,
    color: TEXT_LIGHT,
    lineHeight: 28,
    marginBottom: 20,
    opacity: 0.9,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  bulletItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
    gap: 16,
  },
  bullet: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  bulletDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: BRIGHT_PURPLE,
  },
  bulletText: {
    flex: 1,
    fontSize: 17,
    color: TEXT_LIGHT,
    lineHeight: 28,
    opacity: 0.9,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
});

export default styles;
