import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const isTablet = width > 768;
const isDesktop = width > 992;

// Landing Page Color System
const COLORS = {
  bg: '#08080C',
  bgAlt: '#0C0C12',
  surface: '#12121A',
  surfaceLight: '#1A1A24',
  border: 'rgba(255,255,255,0.06)',
  borderLight: 'rgba(255,255,255,0.1)',
  primary: '#A78BFA',
  primaryDark: '#8B5CF6',
  primaryLight: '#C4B5FD',
  accent: '#6366F1',
  white: '#FFFFFF',
  textPrimary: 'rgba(255,255,255,0.95)',
  textSecondary: 'rgba(255,255,255,0.6)',
  textMuted: 'rgba(255,255,255,0.4)',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  gradient: {
    flex: 1,
  },
  contentContainer: {
    flex: 1,
    flexDirection: isDesktop ? 'row' : 'column',
  },
  sidebar: {
    width: isDesktop ? 320 : '100%',
    padding: isDesktop ? 32 : 24,
    backgroundColor: COLORS.surface,
    borderRightWidth: isDesktop ? 1 : 0,
    borderRightColor: COLORS.border,
    borderBottomWidth: isDesktop ? 0 : 1,
    borderBottomColor: COLORS.border,
    ...Platform.select({
      web: {
        backdropFilter: 'blur(20px)',
      },
    }),
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 40,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: COLORS.surfaceLight,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignSelf: 'flex-start',
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  backButtonHover: {
    borderColor: COLORS.primary,
    ...Platform.select({
      web: {
        boxShadow: '0 4px 12px rgba(167, 139, 250, 0.2)',
      },
    }),
  },
  backArrow: {
    width: 20,
    height: 20,
    position: 'relative',
  },
  backArrowLine: {
    position: 'absolute',
    left: 0,
    top: 9,
    width: 12,
    height: 2,
    backgroundColor: COLORS.white,
  },
  backArrowHead: {
    position: 'absolute',
    left: 0,
    top: 4,
    width: 0,
    height: 0,
    borderTopWidth: 6,
    borderBottomWidth: 6,
    borderLeftWidth: 8,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: COLORS.white,
  },
  backButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '500',
  },
  actionButtons: {
    gap: 16,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceLight,
    gap: 12,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  primaryActionButton: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
    ...Platform.select({
      web: {
        boxShadow: '0 4px 20px rgba(167, 139, 250, 0.3)',
      },
    }),
  },
  actionButtonHover: {
    transform: [{ translateY: -2 }],
    borderColor: COLORS.primary,
    ...Platform.select({
      web: {
        boxShadow: '0 8px 30px rgba(167, 139, 250, 0.4)',
      },
    }),
  },
  actionButtonIcon: {
    width: 24,
    height: 24,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyIcon: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2.5,
    borderColor: COLORS.white,
  },
  interviewIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2.5,
    borderColor: COLORS.white,
  },
  letterIcon: {
    width: 20,
    height: 16,
    borderRadius: 2,
    borderWidth: 2.5,
    borderColor: COLORS.white,
  },
  resumeIcon: {
    width: 16,
    height: 20,
    borderRadius: 2,
    borderWidth: 2.5,
    borderColor: COLORS.white,
  },
  actionButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '600',
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 60,
  },
  contentWrapper: {
    maxWidth: 900,
    alignSelf: 'center',
    width: '100%',
    padding: isDesktop ? 48 : isTablet ? 40 : 32,
    paddingTop: isDesktop ? 60 : 48,
  },
  jobHeader: {
    marginBottom: 48,
    paddingBottom: 32,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  jobHeaderLeft: {
    flexDirection: 'row',
    gap: 20,
    flex: 1,
  },
  companyLogo: {
    width: 80,
    height: 80,
    borderRadius: 20,
    backgroundColor: 'rgba(167, 139, 250, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  companyLogoText: {
    fontSize: 32,
    fontWeight: '700',
    color: COLORS.primary,
  },
  jobHeaderContent: {
    flex: 1,
  },
  jobHeaderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  companyName: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  matchBadge: {
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.3)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  matchScore: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.primary,
  },
  matchLabel: {
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  jobTitle: {
    fontSize: isDesktop ? 36 : isTablet ? 32 : 28,
    fontWeight: '700',
    color: COLORS.white,
    marginBottom: 20,
    lineHeight: isDesktop ? 44 : isTablet ? 40 : 36,
    letterSpacing: -0.5,
  },
  jobMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
  },
  jobMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  metaIcon: {
    width: 20,
    height: 20,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
    opacity: 0.7,
  },
  typeIcon: {
    width: 16,
    height: 16,
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
    transform: [{ rotate: '45deg' }],
    opacity: 0.7,
  },
  moneyIcon: {
    width: 16,
    height: 16,
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
    transform: [{ rotate: '45deg' }],
    opacity: 0.7,
  },
  metaText: {
    fontSize: 15,
    color: COLORS.textSecondary,
  },
  bookmarkButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: COLORS.surfaceLight,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  bookmarkIcon: {
    width: 24,
    height: 24,
    position: 'relative',
  },
  bookmarkIconActive: {
    opacity: 1,
  },
  bookmarkShape: {
    width: 20,
    height: 20,
    borderLeftWidth: 2.5,
    borderRightWidth: 2.5,
    borderTopWidth: 2.5,
    borderBottomWidth: 8,
    borderColor: COLORS.textSecondary,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    opacity: 0.6,
  },
  section: {
    marginBottom: 48,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 24,
  },
  sectionIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(167, 139, 250, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  aboutIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2.5,
    borderColor: COLORS.primary,
  },
  responsibilitiesIcon: {
    width: 28,
    height: 28,
    borderWidth: 2.5,
    borderColor: COLORS.primary,
    transform: [{ rotate: '45deg' }],
  },
  qualificationsIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2.5,
    borderColor: COLORS.primary,
  },
  sectionHeading: {
    fontSize: isDesktop ? 28 : 24,
    fontWeight: '700',
    color: COLORS.white,
  },
  paragraph: {
    fontSize: 17,
    color: COLORS.textSecondary,
    lineHeight: 28,
    marginBottom: 20,
  },
  sectionSubtext: {
    fontSize: 17,
    color: COLORS.textSecondary,
    lineHeight: 28,
    marginBottom: 20,
  },
  bulletItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
    gap: 16,
  },
  bullet: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  bulletDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.primary,
  },
  bulletText: {
    flex: 1,
    fontSize: 17,
    color: COLORS.textSecondary,
    lineHeight: 28,
  },
});

export default styles;
