import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const isTablet = width > 768;
const isDesktop = width > 992;

const DARK_PURPLE = '#1F1C2F';
const LIGHT_PURPLE = '#8B7AB8';
const BRIGHT_PURPLE = '#A78BFA';
const WHITE = '#ffffff';
const TEXT_LIGHT = '#D1D5DB';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DARK_PURPLE,
  },
  gradient: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: isDesktop ? 48 : isTablet ? 32 : 24,
    paddingTop: isDesktop ? 60 : 48,
    paddingBottom: 60,
    maxWidth: 1400,
    alignSelf: 'center',
    width: '100%',
  },
  heroSection: {
    marginBottom: 40,
    alignItems: 'center',
  },
  heroContent: {
    alignItems: 'center',
    maxWidth: 800,
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.3)',
    marginBottom: 20,
    gap: 8,
  },
  badgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: BRIGHT_PURPLE,
  },
  badgeText: {
    fontSize: 13,
    fontWeight: '600',
    color: TEXT_LIGHT,
    letterSpacing: 0.5,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  heroTitle: {
    fontSize: isDesktop ? 56 : isTablet ? 48 : 36,
    fontWeight: 'bold',
    color: WHITE,
    marginBottom: 16,
    textAlign: 'center',
    lineHeight: isDesktop ? 64 : isTablet ? 56 : 44,
    fontFamily: Platform.select({
      web: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
      default: 'sans-serif',
    }),
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 20,
  },
  heroTitleAccent: {
    color: TEXT_LIGHT,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
  },
  heroDescription: {
    fontSize: 18,
    color: TEXT_LIGHT,
    textAlign: 'center',
    opacity: 0.9,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  statsBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2D1B3D',
    borderRadius: 16,
    padding: 24,
    marginBottom: 40,
    borderWidth: 1.5,
    borderColor: 'rgba(139, 122, 184, 0.2)',
    gap: 32,
    flexWrap: 'wrap',
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: 32,
    fontWeight: 'bold',
    color: TEXT_LIGHT,
    marginBottom: 4,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  statLabel: {
    fontSize: 14,
    color: TEXT_LIGHT,
    opacity: 0.8,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: 'rgba(139, 122, 184, 0.3)',
  },
  tabsSection: {
    marginBottom: 32,
    width: '100%',
  },
  tabsContainer: {
    flexDirection: 'row',
    gap: 16,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 16,
    backgroundColor: 'rgba(139, 122, 184, 0.1)',
    borderWidth: 1.5,
    borderColor: 'rgba(139, 122, 184, 0.3)',
    gap: 10,
    position: 'relative',
    minWidth: 180,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  tabActive: {
    backgroundColor: LIGHT_PURPLE,
    borderColor: LIGHT_PURPLE,
    shadowColor: LIGHT_PURPLE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  tabText: {
    color: TEXT_LIGHT,
    fontSize: 15,
    fontWeight: '500',
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  tabTextActive: {
    color: WHITE,
    fontWeight: '600',
  },
  tabIndicator: {
    position: 'absolute',
    bottom: 0,
    left: '50%',
    marginLeft: -20,
    width: 40,
    height: 3,
    borderRadius: 2,
    backgroundColor: WHITE,
  },
  checkmarkContainer: {
    width: 18,
    height: 18,
    position: 'relative',
  },
  checkmarkLine1: {
    position: 'absolute',
    left: 4,
    bottom: 6,
    width: 8,
    height: 2.5,
    backgroundColor: WHITE,
    transform: [{ rotate: '-45deg' }],
  },
  checkmarkLine2: {
    position: 'absolute',
    left: 6,
    bottom: 4,
    width: 10,
    height: 2.5,
    backgroundColor: WHITE,
    transform: [{ rotate: '45deg' }],
  },
  searchSection: {
    marginBottom: 40,
    width: '100%',
    alignItems: 'center',
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: WHITE,
    borderRadius: 20,
    paddingHorizontal: 24,
    paddingVertical: 18,
    width: '100%',
    maxWidth: 1000,
    borderWidth: 2,
    borderColor: 'rgba(139, 122, 184, 0.2)',
    shadowColor: LIGHT_PURPLE,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
      },
    }),
  },
  searchBarFocused: {
    borderColor: BRIGHT_PURPLE,
    shadowOpacity: 0.3,
    shadowRadius: 28,
    ...Platform.select({
      web: {
        boxShadow: `0 12px 40px rgba(167, 139, 250, 0.4)`,
      },
    }),
  },
  searchIconContainer: {
    marginRight: 20,
  },
  searchIcon: {
    width: 24,
    height: 24,
    position: 'relative',
  },
  searchIconCircle: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 3,
    borderColor: '#6B7280',
    top: 0,
    left: 0,
  },
  searchIconLine: {
    position: 'absolute',
    width: 10,
    height: 3,
    backgroundColor: '#6B7280',
    transform: [{ rotate: '45deg' }],
    bottom: 2,
    right: 2,
  },
  searchInput: {
    flex: 1,
    color: '#1F2937',
    fontSize: 17,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  searchDivider: {
    width: 1,
    height: 32,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 20,
  },
  searchFilters: {
    flexDirection: 'row',
    gap: 12,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: LIGHT_PURPLE,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    gap: 8,
    ...Platform.select({
      web: {
        transition: 'all 0.2s ease',
        cursor: 'pointer',
      },
    }),
  },
  filterChipText: {
    color: WHITE,
    fontSize: 14,
    fontWeight: '600',
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  filterArrowIcon: {
    width: 12,
    height: 12,
    position: 'relative',
  },
  filterArrowUp: {
    position: 'absolute',
    top: 0,
    left: 4,
    width: 0,
    height: 0,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderBottomWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: WHITE,
  },
  filterArrowDown: {
    position: 'absolute',
    bottom: 0,
    left: 4,
    width: 0,
    height: 0,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: WHITE,
  },
  tailoredSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2D1B3D',
    borderRadius: 20,
    padding: 24,
    marginBottom: 40,
    borderWidth: 1.5,
    borderColor: 'rgba(167, 139, 250, 0.3)',
    gap: 20,
  },
  tailoredIconContainer: {
    width: 64,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tailoredIcon: {
    width: 48,
    height: 48,
    position: 'relative',
  },
  tailoredCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 3,
    borderColor: BRIGHT_PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tailoredStar: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: BRIGHT_PURPLE,
    transform: [{ rotate: '45deg' }],
  },
  tailoredContent: {
    flex: 1,
  },
  tailoredTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: WHITE,
    marginBottom: 6,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  tailoredText: {
    fontSize: 15,
    color: TEXT_LIGHT,
    lineHeight: 22,
    opacity: 0.9,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  jobsList: {
    gap: 24,
  },
  jobCard: {
    backgroundColor: '#2D1B3D',
    borderRadius: 24,
    padding: 28,
    borderWidth: 1.5,
    borderColor: 'rgba(139, 122, 184, 0.2)',
    shadowColor: LIGHT_PURPLE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 6,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  jobCardHover: {
    transform: [{ translateY: -4 }],
    borderColor: BRIGHT_PURPLE,
    shadowOpacity: 0.3,
    shadowRadius: 24,
    backgroundColor: '#3D2B4D',
    ...Platform.select({
      web: {
        boxShadow: `0 12px 32px rgba(167, 139, 250, 0.3)`,
      },
    }),
  },
  jobCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  jobCardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    flex: 1,
  },
  companyLogo: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(167, 139, 250, 0.3)',
  },
  companyLogoText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: TEXT_LIGHT,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  jobCardHeaderContent: {
    flex: 1,
  },
  jobCardTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: WHITE,
    marginBottom: 6,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  jobCardCompany: {
    fontSize: 16,
    color: TEXT_LIGHT,
    opacity: 0.8,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  jobCardHeaderRight: {
    alignItems: 'flex-end',
    gap: 12,
  },
  matchBadge: {
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.3)',
    alignItems: 'center',
  },
  matchScore: {
    fontSize: 18,
    fontWeight: 'bold',
    color: TEXT_LIGHT,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  matchLabel: {
    fontSize: 11,
    color: TEXT_LIGHT,
    opacity: 0.7,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  bookmarkButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookmarkIcon: {
    width: 24,
    height: 24,
    position: 'relative',
  },
  bookmarkShape: {
    width: 20,
    height: 20,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 2,
    borderBottomWidth: 8,
    borderColor: TEXT_LIGHT,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    opacity: 0.6,
  },
  jobCardDetails: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
    marginBottom: 20,
  },
  jobDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailIcon: {
    width: 20,
    height: 20,
    position: 'relative',
  },
  locationIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: TEXT_LIGHT,
    opacity: 0.6,
  },
  moneyIcon: {
    width: 16,
    height: 16,
    borderWidth: 2,
    borderColor: TEXT_LIGHT,
    transform: [{ rotate: '45deg' }],
    opacity: 0.6,
  },
  timeIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: TEXT_LIGHT,
    opacity: 0.6,
  },
  jobCardLocation: {
    fontSize: 15,
    color: TEXT_LIGHT,
    opacity: 0.8,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  jobCardRate: {
    fontSize: 15,
    color: TEXT_LIGHT,
    opacity: 0.8,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  jobCardPosted: {
    fontSize: 15,
    color: TEXT_LIGHT,
    opacity: 0.8,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  jobTypes: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  jobTypeTag: {
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.3)',
  },
  jobTypeText: {
    fontSize: 13,
    color: TEXT_LIGHT,
    fontWeight: '500',
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  jobCardDescription: {
    fontSize: 15,
    color: TEXT_LIGHT,
    lineHeight: 22,
    opacity: 0.85,
    marginBottom: 20,
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  jobCardFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  viewDetailsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: LIGHT_PURPLE,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  viewDetailsText: {
    color: WHITE,
    fontSize: 15,
    fontWeight: '600',
    fontFamily: Platform.select({
      web: 'system-ui, sans-serif',
      default: 'sans-serif',
    }),
  },
  viewDetailsArrow: {
    width: 16,
    height: 16,
    position: 'relative',
  },
  arrowLine: {
    position: 'absolute',
    left: 0,
    top: 7,
    width: 12,
    height: 2,
    backgroundColor: WHITE,
  },
  arrowHead: {
    position: 'absolute',
    right: 0,
    top: 4,
    width: 0,
    height: 0,
    borderTopWidth: 4,
    borderBottomWidth: 4,
    borderLeftWidth: 6,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: WHITE,
  },
});

export default styles;
