import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const DARK_PURPLE = '#1F1C2F';
const LIGHT_PURPLE = '#8B7AB8';
const WHITE = '#ffffff';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DARK_PURPLE,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingTop: 40,
  },
  tabsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 40,
    flexWrap: 'wrap',
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: DARK_PURPLE,
    borderWidth: 1,
    borderColor: LIGHT_PURPLE,
    gap: 8,
  },
  tabActive: {
    backgroundColor: LIGHT_PURPLE,
    borderColor: LIGHT_PURPLE,
  },
  tabText: {
    color: WHITE,
    fontSize: 16,
    fontWeight: '500',
  },
  tabTextActive: {
    color: WHITE,
  },
  checkmark: {
    color: WHITE,
    fontSize: 14,
    fontWeight: 'bold',
  },
  heroTitle: {
    fontSize: 48,
    fontWeight: 'bold',
    color: WHITE,
    marginBottom: 30,
    textAlign: 'center',
    fontFamily: Platform.select({
      web: 'Georgia, serif',
      default: 'serif',
    }),
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#374151',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  searchIcon: {
    width: 20,
    height: 20,
    marginRight: 12,
    position: 'relative',
  },
  searchIconCircle: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#9CA3AF',
    top: 0,
    left: 0,
  },
  searchIconLine: {
    position: 'absolute',
    width: 8,
    height: 2,
    backgroundColor: '#9CA3AF',
    transform: [{ rotate: '45deg' }],
    bottom: 2,
    right: 2,
  },
  searchInput: {
    flex: 1,
    color: WHITE,
    fontSize: 16,
  },
  searchFilters: {
    flexDirection: 'row',
    gap: 8,
    marginLeft: 12,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: LIGHT_PURPLE,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    gap: 6,
  },
  filterChipText: {
    color: WHITE,
    fontSize: 14,
    fontWeight: '500',
  },
  filterArrowIcon: {
    width: 12,
    height: 12,
    position: 'relative',
  },
  filterArrowUp: {
    position: 'absolute',
    top: 0,
    left: 4,
    width: 0,
    height: 0,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderBottomWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: WHITE,
  },
  filterArrowDown: {
    position: 'absolute',
    bottom: 0,
    left: 4,
    width: 0,
    height: 0,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: WHITE,
  },
  tailoredSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2D1B3D',
    padding: 20,
    borderRadius: 12,
    marginBottom: 30,
    gap: 16,
  },
  tailoredIcon: {
    width: 40,
    height: 40,
  },
  tailoredCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: DARK_PURPLE,
    borderWidth: 2,
    borderColor: WHITE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tailoredStar: {
    width: 16,
    height: 16,
    borderWidth: 2,
    borderColor: WHITE,
    transform: [{ rotate: '45deg' }],
  },
  tailoredText: {
    flex: 1,
    color: WHITE,
    fontSize: 16,
    lineHeight: 24,
  },
  jobsList: {
    gap: 20,
  },
  jobCard: {
    backgroundColor: '#2D1B3D',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: LIGHT_PURPLE,
    ...Platform.select({
      web: {
        cursor: 'pointer',
      },
    }),
  },
  jobCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  companyLogo: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: LIGHT_PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  companyLogoText: {
    color: WHITE,
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  bookmarkButton: {
    padding: 8,
  },
  bookmarkIcon: {
    width: 20,
    height: 20,
    position: 'relative',
  },
  bookmarkShape: {
    position: 'absolute',
    width: 16,
    height: 20,
    borderWidth: 2,
    borderColor: WHITE,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 0,
    backgroundColor: 'transparent',
  },
  jobCardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: WHITE,
    marginBottom: 8,
  },
  jobCardCompany: {
    fontSize: 16,
    color: WHITE,
    marginBottom: 4,
    fontWeight: '500',
  },
  jobCardLocation: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 12,
  },
  jobCardRate: {
    fontSize: 16,
    fontWeight: '600',
    color: WHITE,
    marginBottom: 12,
  },
  jobTypes: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  jobTypeTag: {
    backgroundColor: '#374151',
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  jobTypeText: {
    color: WHITE,
    fontSize: 12,
    fontWeight: '500',
  },
  jobCardDescription: {
    fontSize: 14,
    color: '#D1D5DB',
    lineHeight: 20,
    marginBottom: 16,
  },
  jobCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  jobCardPosted: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  moreButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: LIGHT_PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moreButtonArrow: {
    width: 16,
    height: 16,
    position: 'relative',
  },
  moreButtonLine: {
    position: 'absolute',
    left: 0,
    top: 7,
    width: 12,
    height: 2,
    backgroundColor: WHITE,
  },
  moreButtonHead: {
    position: 'absolute',
    right: 0,
    top: 4,
    width: 0,
    height: 0,
    borderTopWidth: 4,
    borderBottomWidth: 4,
    borderLeftWidth: 6,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: WHITE,
  },
});

export default styles;
