import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const isTablet = width > 768;
const isDesktop = width > 992;

// Landing Page Color System
const COLORS = {
  bg: '#08080C',
  bgAlt: '#0C0C12',
  surface: '#12121A',
  surfaceLight: '#1A1A24',
  border: 'rgba(255,255,255,0.06)',
  borderLight: 'rgba(255,255,255,0.1)',
  primary: '#A78BFA',
  primaryDark: '#8B5CF6',
  primaryLight: '#C4B5FD',
  accent: '#6366F1',
  white: '#FFFFFF',
  textPrimary: 'rgba(255,255,255,0.95)',
  textSecondary: 'rgba(255,255,255,0.6)',
  textMuted: 'rgba(255,255,255,0.4)',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  gradient: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: isDesktop ? 48 : isTablet ? 32 : 24,
    paddingTop: isDesktop ? 60 : 48,
    paddingBottom: 60,
    maxWidth: 1400,
    alignSelf: 'center',
    width: '100%',
  },
  heroSection: {
    marginBottom: 40,
    alignItems: 'center',
  },
  heroContent: {
    alignItems: 'center',
    maxWidth: 800,
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(167, 139, 250, 0.1)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.2)',
    marginBottom: 20,
    gap: 8,
  },
  badgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.primary,
    ...Platform.select({
      web: {
        boxShadow: '0 0 12px rgba(167, 139, 250, 0.6)',
      },
    }),
  },
  badgeText: {
    fontSize: 13,
    fontWeight: '500',
    color: COLORS.primary,
    letterSpacing: 0.5,
  },
  heroTitle: {
    fontSize: isDesktop ? 56 : isTablet ? 48 : 36,
    fontWeight: '700',
    color: COLORS.white,
    marginBottom: 16,
    textAlign: 'center',
    lineHeight: isDesktop ? 64 : isTablet ? 56 : 44,
    letterSpacing: -1,
  },
  heroTitleAccent: {
    color: COLORS.primary,
  },
  heroDescription: {
    fontSize: 18,
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 28,
  },
  statsBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 24,
    marginBottom: 40,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 32,
    flexWrap: 'wrap',
    ...Platform.select({
      web: {
        backdropFilter: 'blur(20px)',
      },
    }),
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: 32,
    fontWeight: '700',
    color: COLORS.primary,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: COLORS.border,
  },
  tabsSection: {
    marginBottom: 32,
    width: '100%',
  },
  tabsContainer: {
    flexDirection: 'row',
    gap: 16,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 10,
    position: 'relative',
    minWidth: 180,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  tabActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
    ...Platform.select({
      web: {
        boxShadow: '0 4px 20px rgba(167, 139, 250, 0.3)',
      },
    }),
  },
  tabText: {
    color: COLORS.textSecondary,
    fontSize: 15,
    fontWeight: '500',
  },
  tabTextActive: {
    color: COLORS.white,
    fontWeight: '600',
  },
  tabIndicator: {
    position: 'absolute',
    bottom: 0,
    left: '50%',
    marginLeft: -20,
    width: 40,
    height: 3,
    borderRadius: 2,
    backgroundColor: COLORS.white,
  },
  checkmarkContainer: {
    width: 18,
    height: 18,
    position: 'relative',
  },
  checkmarkLine1: {
    position: 'absolute',
    left: 4,
    bottom: 6,
    width: 8,
    height: 2.5,
    backgroundColor: COLORS.white,
    transform: [{ rotate: '-45deg' }],
  },
  checkmarkLine2: {
    position: 'absolute',
    left: 6,
    bottom: 4,
    width: 10,
    height: 2.5,
    backgroundColor: COLORS.white,
    transform: [{ rotate: '45deg' }],
  },
  searchSection: {
    marginBottom: 40,
    width: '100%',
    alignItems: 'center',
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    paddingHorizontal: 24,
    paddingVertical: 18,
    width: '100%',
    maxWidth: 1000,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        backdropFilter: 'blur(20px)',
      },
    }),
  },
  searchBarFocused: {
    borderColor: COLORS.primary,
    ...Platform.select({
      web: {
        boxShadow: '0 8px 30px rgba(167, 139, 250, 0.2)',
      },
    }),
  },
  searchIconContainer: {
    marginRight: 20,
  },
  searchIcon: {
    width: 24,
    height: 24,
    position: 'relative',
  },
  searchIconCircle: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 3,
    borderColor: COLORS.textMuted,
    top: 0,
    left: 0,
  },
  searchIconLine: {
    position: 'absolute',
    width: 10,
    height: 3,
    backgroundColor: COLORS.textMuted,
    transform: [{ rotate: '45deg' }],
    bottom: 2,
    right: 2,
  },
  searchInput: {
    flex: 1,
    color: COLORS.textPrimary,
    fontSize: 17,
  },
  searchDivider: {
    width: 1,
    height: 32,
    backgroundColor: COLORS.border,
    marginHorizontal: 20,
  },
  searchFilters: {
    flexDirection: 'row',
    gap: 12,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surfaceLight,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    gap: 8,
    ...Platform.select({
      web: {
        transition: 'all 0.2s ease',
        cursor: 'pointer',
      },
    }),
  },
  filterChipText: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: '500',
  },
  filterArrowIcon: {
    width: 12,
    height: 12,
    position: 'relative',
  },
  filterArrowUp: {
    position: 'absolute',
    top: 0,
    left: 4,
    width: 0,
    height: 0,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderBottomWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: COLORS.textPrimary,
  },
  filterArrowDown: {
    position: 'absolute',
    bottom: 0,
    left: 4,
    width: 0,
    height: 0,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: COLORS.textPrimary,
  },
  tailoredSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 24,
    marginBottom: 40,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 20,
    ...Platform.select({
      web: {
        backdropFilter: 'blur(20px)',
      },
    }),
  },
  tailoredIconContainer: {
    width: 64,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tailoredIcon: {
    width: 48,
    height: 48,
    position: 'relative',
  },
  tailoredCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 3,
    borderColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tailoredStar: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: COLORS.primary,
    transform: [{ rotate: '45deg' }],
  },
  tailoredContent: {
    flex: 1,
  },
  tailoredTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.white,
    marginBottom: 6,
  },
  tailoredText: {
    fontSize: 15,
    color: COLORS.textSecondary,
    lineHeight: 22,
  },
  jobsList: {
    gap: 24,
  },
  jobCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    padding: 28,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
        backdropFilter: 'blur(20px)',
      },
    }),
  },
  jobCardHover: {
    transform: [{ translateY: -4 }],
    borderColor: COLORS.primary,
    ...Platform.select({
      web: {
        boxShadow: '0 12px 32px rgba(167, 139, 250, 0.2)',
      },
    }),
  },
  jobCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  jobCardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    flex: 1,
  },
  companyLogo: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: 'rgba(167, 139, 250, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  companyLogoText: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.primary,
  },
  jobCardHeaderContent: {
    flex: 1,
  },
  jobCardTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: COLORS.white,
    marginBottom: 6,
  },
  jobCardCompany: {
    fontSize: 16,
    color: COLORS.textSecondary,
  },
  jobCardHeaderRight: {
    alignItems: 'flex-end',
    gap: 12,
  },
  matchBadge: {
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.3)',
    alignItems: 'center',
  },
  matchScore: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.primary,
  },
  matchLabel: {
    fontSize: 11,
    color: COLORS.textSecondary,
  },
  bookmarkButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookmarkIcon: {
    width: 24,
    height: 24,
    position: 'relative',
  },
  bookmarkShape: {
    width: 20,
    height: 20,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 2,
    borderBottomWidth: 8,
    borderColor: COLORS.textSecondary,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    opacity: 0.6,
  },
  jobCardDetails: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
    marginBottom: 20,
  },
  jobDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailIcon: {
    width: 20,
    height: 20,
    position: 'relative',
  },
  locationIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
    opacity: 0.6,
  },
  moneyIcon: {
    width: 16,
    height: 16,
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
    transform: [{ rotate: '45deg' }],
    opacity: 0.6,
  },
  timeIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
    opacity: 0.6,
  },
  jobCardLocation: {
    fontSize: 15,
    color: COLORS.textSecondary,
  },
  jobCardRate: {
    fontSize: 15,
    color: COLORS.textSecondary,
  },
  jobCardPosted: {
    fontSize: 15,
    color: COLORS.textSecondary,
  },
  jobTypes: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  jobTypeTag: {
    backgroundColor: 'rgba(167, 139, 250, 0.1)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.2)',
  },
  jobTypeText: {
    fontSize: 13,
    color: COLORS.primary,
    fontWeight: '500',
  },
  jobCardDescription: {
    fontSize: 15,
    color: COLORS.textSecondary,
    lineHeight: 22,
    marginBottom: 20,
  },
  jobCardFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  viewDetailsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
    ...Platform.select({
      web: {
        transition: 'all 0.3s ease',
        cursor: 'pointer',
      },
    }),
  },
  viewDetailsText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '600',
  },
  viewDetailsArrow: {
    width: 16,
    height: 16,
    position: 'relative',
  },
  arrowLine: {
    position: 'absolute',
    left: 0,
    top: 7,
    width: 12,
    height: 2,
    backgroundColor: COLORS.white,
  },
  arrowHead: {
    position: 'absolute',
    right: 0,
    top: 4,
    width: 0,
    height: 0,
    borderTopWidth: 4,
    borderBottomWidth: 4,
    borderLeftWidth: 6,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: COLORS.white,
  },
});

export default styles;
