"""
AI prompts for interview generation and evaluation
"""

from .question_generation import (
    QUESTION_GENERATION_SYSTEM_PROMPT,
    BEHAVIORAL_QUESTION_EXAMPLES,
    TECHNICAL_QUESTION_EXAMPLES,
)

from .answer_evaluation import (
    EVALUATION_SYSTEM_PROMPT,
    BEHAVIORAL_EVALUATION_PROMPT,
    TECHNICAL_EVALUATION_PROMPT,
    STAR_ANALYSIS_PROMPT,
)

__all__ = [
    "QUESTION_GENERATION_SYSTEM_PROMPT",
    "BEHAVIORAL_QUESTION_EXAMPLES",
    "TECHNICAL_QUESTION_EXAMPLES",
    "EVALUATION_SYSTEM_PROMPT",
    "BEHAVIORAL_EVALUATION_PROMPT",
    "TECHNICAL_EVALUATION_PROMPT",
    "STAR_ANALYSIS_PROMPT",
]
